### PR TITLE
add y(a)ml to editorconfig

### PR DESCRIPTION
**Pull request by woodiertexas**

### CODE REVIEW

**Review by eristhea — CHANGES_REQUESTED** [review]
why would we set yaml style if we're not shipping actions?

**Comment by woodiertexas** [comment]
futureproofing and people generally use github actions for their mods

**Review by eristhea — APPROVED** [review]
sure, this seems to match the style on other quilt repos (https://github.com/search?q=org%3Aquiltmc+yml+language%3AEditorConfig&type=code&l=EditorConfig)

**Comment by woodiertexas** [comment]
> sure, this seems to match the style on other quilt repos (https://github.com/search?q=org%3Aquiltmc+yml+language%3AEditorConfig&type=code&l=EditorConfig)

the cozy repo should be using `[*.{yml,yaml}]` instead of `[*.yml]` imo

**Pull request merged**
