### PR TITLE
Update gradle-wrapper.properties

### PR DESCRIPTION
**Pull request by BirbGodWrench**
this is such a simple change and it fixes the entire thing.

### CODE REVIEW

**Comment by 770grappenmaker** [comment]
What does it fix?

**Comment by OroArmor** [comment]
Minecraft 1.21 requires java 21 meaning gradle 8.8.

**Comment by BirbGodWrench** [comment]
so does 1.20.1 (or at least quilt 1.20.1)

**Comment by BirbGodWrench** [comment]
(also sorry for being vague i dont use github very often)

**Comment by woodiertexas** [comment]
Tbh, could go to gradle 8.9 instead of stopping at 8.8

**Comment by BirbGodWrench** [comment]
> Tbh, could go to gradle 8.9 instead of stopping at 8.8

Tbh I didn’t know gradle 8.9 existed…

**Pull request merged**
