### PR TITLE
add a mod id constant in `ExampleMod.java`

### PR DESCRIPTION
**Pull request by eristhea**
this is pretty much needed for any mod that does anything. users who won't be doing registry or config stuff are definitely savvy enough to understand that they don't need this

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]
I wish there was a good way to set this using the `mod` passed in with the initalizer. but then it wouldnt be a psfs field

**Comment by eristhea** [comment]
maybe we could throw an exception if the psfs doesn't match the mod container?

**Comment by eristhea** [comment]
@OroArmor please reply above!

**Comment by OroArmor** [comment]
that could work, but i worry people wont change both the qmj and the field in the psfs. There isnt really a good solution here

**Comment by eristhea** [comment]
what I'm proposing is that we add a block like this:
```
// the following block validates that you've updated both the quilt.mod.json file and MOD_ID field when you change your mod ID. if you're familiar with making mods, feel free to remove this!
if (!mod.id().equals(MOD_ID)) {
    throw new RuntimeException("mod IDs in quilt.mod.json and MOD_ID field do not match! (quilt.mod.json: qmj mod id; MOD_ID: MOD_ID);
}
```

**Comment by OroArmor** [comment]
```java
// the following block validates that you've updated both the quilt.mod.json file and MOD_ID field when you change your mod ID. if you're familiar with making mods, feel free to remove this!
if (!mod.id().equals(MOD_ID)) {
    throw new RuntimeException(String.format("mod IDs in quilt.mod.json and MOD_ID field do not match! (quilt.mod.json: %s; MOD_ID: %s", mod.id(), MOD_ID);
}
```

**Comment by eristhea** [comment]
oro is you fixing my pseudocode meaning you agree with my idea

**Comment by OroArmor** [comment]
perhaps

**Comment by eristhea** [comment]
as the author of this I'm kinda rethinking it. we can pass the modcontainer for registration stuff, so I'm not sure when this is relevant

**Pull request closed without merging**
