### PR TITLE
Automatically append Minecraft version to mod version

### PR DESCRIPTION
**Pull request by triphora**

### CODE REVIEW

**Review by EnnuiL — COMMENTED** [review]
Hm, I'm conflicted about it; I was already thinking of many reasons why to not use it, but maybe there isn't really one?

**Comment by triphora** [comment]
It makes life easier for people, imo, and I don't see a reason not to do it

**Comment by Gaming32** [comment]
Please do this. The absence of this is honestly my second biggest annoyance with the template.

**Comment by EnnuiL** [comment]
oh well, let's see how this will end going

**Pull request merged**
